build:
  environment:
    php:
      version: "7.1"

  nodes:
    tests-and-coverage:
      tests:
        override:
        -
          command: vendor/bin/phpunit --coverage-clover /tmp/coverage.xml
          coverage:
            file: /tmp/coverage.xml
            format: clover

    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - "app/"
    - "config/"
    - "bin/"
    - "storage/"
    - "tests/"
    - "vendor/"
